version: "3.3"
services:
  db:
    container_name: postgres
    image: postgres:14.10-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - newsletter

  init-db:
    container_name: db-init-container
    env_file:
      .env
    build:
      context: ./
      dockerfile: init-dockerfile
    depends_on:
      db:
        condition: service_started
    networks:
      - newsletter

  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      .env
    networks:
      - newsletter
    depends_on:
      db:
        condition: service_started
      init-db:
        condition: service_completed_successfully
    ports:
      - "8000:80"

networks:
  newsletter:
