"""Initial subscription table

Revision ID: 69b942ff6dcb
Revises: 
Create Date: 2024-02-03 21:39:05.839162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b942ff6dcb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('user_identifier', sa.String(length=64), nullable=False, comment='User Identifier'),
    sa.Column('sub_type', sa.Enum('email', 'sns', name='subtypeenum'), nullable=False, comment='Subscription Type'),
    sa.Column('sub_address', sa.String(length=256), nullable=False, comment='Subscription Address'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is active'),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True, comment='Create Timestamp'),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True, comment='Update Timestamp'),
    sa.Column('meta_flag', sa.String(), nullable=True, comment='Meta Flag'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_type', 'sub_address', name='sub_type_sub_address_uix')
    )
    op.create_index(op.f('ix_subscription_is_active'), 'subscription', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscription_user_identifier'), 'subscription', ['user_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_user_identifier'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_is_active'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
