"""Add column is_promotion

Revision ID: 6d2a61af9d15
Revises: c086f79199d8
Create Date: 2024-02-05 00:22:57.880371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2a61af9d15'
down_revision: Union[str, None] = 'c086f79199d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('is_promotion', sa.Boolean(), nullable=True, comment='Is Promotion'))
    op.create_index(op.f('ix_subscription_is_promotion'), 'subscription', ['is_promotion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_is_promotion'), table_name='subscription')
    op.drop_column('subscription', 'is_promotion')
    # ### end Alembic commands ###
