"""Add user_sub_type_uix

Revision ID: c086f79199d8
Revises: 680ce427b0f8
Create Date: 2024-02-04 20:38:41.443563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c086f79199d8'
down_revision: Union[str, None] = '680ce427b0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_sub_type_uix', 'subscription', ['user_identifier', 'sub_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_sub_type_uix', 'subscription', type_='unique')
    # ### end Alembic commands ###
